apiVersion: v1
kind: Service
metadata:
  name: impress-service
spec:
  type: LoadBalancer
  selector:
    app: impress
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: impress-deployment
  labels:
    app: impress
spec:
  replicas: 3
  selector:
    matchLabels:
      app: impress
  template:
    metadata:
      labels:
        app: impress
    spec:
      containers:
      - name: devin-test
        image: devinburnette/devin-impress:latest
        ports:
        - containerPort: 80
